### ISSUE TITLE
clustersecretstores kind type not functional

### ISSUE THREAD

**Issue by eperdeme** [iponweb/charts#2]
Hello,

Was looking at the external-secrets metadata chart and attempted to use clustersecretstores. However so far it looks to alwats set ExternalSecret knd type not clustersecretstores.

I'm not 100% sure how all thse spec and valiators works but the issue appears to be in https://github.com/iponweb/charts/blob/main/charts/meta-external-secrets/templates/generated/_settings.tpl#L13

Presume the yaml looks like
```
clustersecretstores:
  main:
    spec:
      provider:
        aws:
          service: ParameterStore
          region: eu-west-1
          auth:
            jwt:
              serviceAccountRef:
                name: external-secrets
                namespace: external-secrets
  main2:
    spec:
      provider:
        aws:
          service: SecretsManager
          region: eu-west-1
          auth:
            jwt:
              serviceAccountRef:
                name: external-secrets
                namespace: external-secrets```

**Comment by vladarts** [comment]
Fixed in the 0.7.3 chart version. sorry for the late reaction
